print('Faça um prgrama que leia algo pelo teclado e mostre na tela seu tipo primitivo e todas as informaçoes sobre ele.')
n = input('Digite um caractere sem acrescentar espaços: ')
print('Qual seu tipo primitivo?', type(n))
print('Esse caractere contém apenas letras minúsculas?', n.islower())
print('Os caractéres inseridos sao apenas alfanuméricos?', n.isalnum())
print('Os caractéres estao todos em maiúsculo?', n.isupper())
print('Os caracteres inseridos fazem exclusivamente parte do alfabeto?', n.isalpha())
print('Os carácteres apresentados contém números decimais?', n.isdecimal())
print('Os caracteres apresentados estao exclusivamente listados na lista ascii?', n.isascii())
print('Os caracteres apresentados sao palavras de identificadores?', n.isidentifier())
print('Os caracteres apresentados sao excusivamente numericos?', n.isnumeric())
print('Os caracteres apresentados sao imprimiveis?', n.isprintable())
print('Os caracteres a seguir sao apenas espaços sem branco?', n.isspace())
print('Os caracteres a seguir seguem as regras de titulo?', n.istitle())
